import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "Wisp",
    template: "%s | Wisp AI",
  },
  description:
    "Generate production-ready Roblox scripts, systems, and instances with AI. Built by Wisp Studios.",
  keywords: [

    "wisp",
    "wisp ai",
    "wisp studios",
    "wisp roblox",
    "wisp script generator",
    "wisp luau",
    "wisp.lol",
    "wisp dash",
    "dash.wisp.lol",
    "wisp ai beta",
    "wisp ai free",
    "wisp ai roblox",
    "wisp ai studio",
    "wisp ai plugin",
    "wisp is so goated",
    "wisp better than chatgpt",
    "wisp studios ai",
    "wisp ai discord",
    "wisp ai review",
    "wisp ai tutorial",


    "roblox",
    "luau",
    "scripting",
    "scripts",
    "ai",
    "free",
    "generator",
    "automation",
    "coding",
    "developer",
    "studio",
    "plugin",
    "grok",
    "claude",
    "gemini",
    "copilot",
    "chatgpt",
    "openai",
    "cursor",
    "windsurf",
    "replit",
    "devin",
    "codeium",
    "tabnine",


    "claude 4.6 sonnet roblox",
    "claude sonnet roblox scripts",
    "claude opus roblox",
    "gpt 4o roblox",
    "gpt 4 roblox scripts",
    "gpt 5 roblox",
    "gemini 2.0 roblox",
    "gemini flash roblox",
    "grok roblox",
    "grok 3 roblox scripts",
    "grok free roblox ai",
    "deepseek roblox",
    "deepseek r1 roblox",
    "llama roblox",
    "mistral roblox",
    "qwen roblox",
    "o3 roblox",
    "o1 roblox",
    "claude 4.6 sonnet",
    "claude 4 roblox",
    "anthropic roblox ai",


    "free roblox ai tool",
    "free luau ai",
    "free roblox script maker",
    "free roblox code generator",
    "free ai for roblox",
    "no cost roblox ai",
    "roblox ai no subscription",
    "roblox scripting tool free no signup",
    "free game dev ai",
    "100% free roblox scripts",
    "free roblox coding assistant",
    "free roblox assistant",
    "free roblox helper",
    "free roblox bot",
    "free roblox ai bot",
    "free roblox script bot",
    "free roblox script writer",
    "free roblox script generator no sign up",
    "free roblox studio ai plugin",
    "free luau code generator no sign up",
    "free roblox ai no login",
    "free roblox ai no paywall",
    "free roblox ai no credit card",
    "free roblox ai no account",
    "free roblox ai open source",
    "free roblox ai tool 2025",
    "free roblox ai tool 2024",
    "free roblox ai generator",
    "free roblox ai writer",
    "free roblox ai coder",
    "free roblox ai scripter",
    "free roblox ai helper",
    "free roblox ai assistant",
    "free roblox dev tool",
    "free roblox developer tool",
    "free roblox developer ai",
    "free roblox developer assistant",
    "free game ai tool",
    "free game script generator",
    "free game coding ai",
    "free indie game ai",
    "free game dev assistant",


    "roblox ai goat",
    "best roblox ai ever",
    "roblox ai no cap",
    "roblox script generator bussin",
    "roblox ai fr fr",
    "roblox ai lowkey fire",
    "roblox ai W",
    "roblox ai actually works",
    "roblox ai that doesnt suck",
    "roblox script generator that actually works",
    "roblox ai better than my scripter friend",
    "fire roblox ai tool",
    "goated roblox ai",
    "roblox ai hits different",
    "roblox ai deadass works",
    "roblox ai insane",
    "roblox ai crazy good",
    "roblox ai op",
    "roblox ai overpowered",
    "roblox ai slaps",
    "roblox ai is built different",
    "roblox ai absolute cinema",
    "roblox ai is real and its free",
    "i cant believe roblox ai is free",
    "roblox ai for broke devs",
    "roblox ai for solo devs",
    "roblox ai for small devs",
    "roblox ai for beginners",
    "roblox ai makes scripting easy",
    "roblox scripting is easy now",
    "roblox scripting cheat code",
    "roblox dev cheat code",
    "roblox game dev shortcut",
    "roblox ai do it for me",
    "just make my roblox script",
    "make roblox script for me",
    "write my roblox script",
    "ai write roblox script please",
    "roblox ai send tweet",
    "roblox ai sheesh",
    "roblox ai based",
    "roblox ai mid",
    "roblox ai not mid actually",
    "roblox ai better than expected",
    "roblox ai surprised me",
    "roblox ai actually goated",
    "roblox ai rizz",
    "roblox ai sigma",
    "roblox ai grindset",
    "roblox ai npc behavior",
    "roblox ai main character",
    "roblox ai carried my game",
    "roblox ai saved my project",
    "roblox ai clutched up",
    "roblox ai no skill issue",
    "roblox ai skill issue solved",
    "roblox ai 67",


    "roblox ai",
    "roblox ai tools",
    "roblox ai tools free",
    "roblox script generator",
    "roblox ai assistant",
    "roblox coding tool",
    "roblox scripting help",
    "roblox developer tools",
    "roblox studio ai",
    "roblox studio tools",
    "roblox automation",
    "roblox ai plugin",
    "roblox studio plugin ai",
    "roblox ai beta",
    "roblox ai 2024",
    "roblox ai 2025",
    "best roblox ai tool 2025",
    "roblox ai script writer 2025",
    "roblox ai saas",
    "roblox ai web app",
    "roblox ai dashboard",
    "roblox ai platform",
    "roblox ai service",
    "roblox ai api",
    "roblox ai oauth",
    "roblox oauth2 login",


    "luau ai",
    "roblox luau ai",
    "luau code generator",
    "luau script generator",
    "luau coding assistant",
    "luau scripting",
    "luau autocomplete",
    "luau syntax",
    "luau helper",
    "luau typed",
    "luau strict mode",
    "luau type checker",
    "luau programming",
    "luau language",
    "luau oop",
    "luau module",
    "luau class",
    "luau ai assistant",
    "luau code writer",
    "luau snippet generator",
    "luau function generator",
    "luau types",
    "luau generics",
    "luau metatables",
    "luau inheritance",
    "luau coroutines",
    "luau pcall",
    "luau xpcall",
    "luau task library",
    "luau buffer",
    "luau vector",
    "luau string library",
    "luau table library",
    "luau math library",
    "luau require",
    "luau module pattern",
    "luau service pattern",
    "luau knit framework",
    "luau flamework",
    "luau roact",
    "luau fusion",
    "luau matter ecs",
    "roblox typescript",
    "roblox ts ai",


    "roblox game scripts",
    "roblox module scripts",
    "roblox remote events",
    "roblox gui generator",
    "roblox leaderboard script",
    "roblox datastore",
    "roblox systems",
    "roblox instances",
    "roblox serverscript",
    "roblox localscript",
    "roblox bindableevents",
    "roblox obby script",
    "roblox tycoon script",
    "roblox fps script",
    "roblox admin script",
    "roblox anticheat",
    "roblox inventory system",
    "roblox shop system",
    "roblox combat system",
    "roblox pet system",
    "roblox currency system",
    "roblox badge script",
    "roblox proximity prompt",
    "roblox tweenservice script",
    "roblox animator script",
    "roblox pathfinding",
    "roblox npc ai",
    "roblox hitbox script",
    "roblox saving data script",
    "roblox round system",
    "roblox map voting script",
    "roblox spectate script",
    "roblox kill brick script",
    "roblox tool script",
    "roblox sword script",
    "roblox gun script",
    "roblox door script",
    "roblox elevator script",
    "roblox vehicle script",
    "roblox ragdoll script",
    "roblox morph script",
    "roblox team script",
    "roblox point system",
    "roblox level system",
    "roblox xp system",
    "roblox achievement script",
    "roblox cutscene script",
    "roblox camera script",
    "roblox day night cycle",
    "roblox weather script",
    "roblox music script",
    "roblox sound script",
    "roblox particle script",
    "roblox lighting script",
    "roblox placement system",
    "roblox building system",
    "roblox crafting system",
    "roblox fishing script",
    "roblox mining script",
    "roblox farming script",
    "roblox trading system",
    "roblox auction system",
    "roblox chat filter script",
    "roblox report system",
    "roblox ban script",
    "roblox kick script",
    "roblox teleport script",
    "roblox zone script",
    "roblox region script",
    "roblox sprint script",
    "roblox stamina script",
    "roblox health regen script",
    "roblox hunger script",
    "roblox status effect script",
    "roblox datastore v2",
    "roblox profileservice",
    "roblox datastore2",
    "roblox leaderstats",
    "roblox kills script",
    "roblox wins script",
    "roblox cash script",
    "roblox gems script",
    "roblox coins script",
    "roblox rank system",
    "roblox group rank script",
    "roblox vip script",
    "roblox gamepass script",
    "roblox developer product script",
    "roblox monetization script",
    "roblox ui script",
    "roblox screenui script",
    "roblox textbutton script",
    "roblox scrollingframe script",
    "roblox billboard gui",
    "roblox surfacegui",
    "roblox dialog script",
    "roblox first person script",
    "roblox third person script",
    "roblox shift to sprint",
    "roblox double jump script",
    "roblox wall jump script",
    "roblox dash script",
    "roblox dodge script",
    "roblox block script",
    "roblox parry script",
    "roblox stun script",
    "roblox knockback script",
    "roblox combo system",
    "roblox skill system",
    "roblox ability system",
    "roblox magic system",
    "roblox spell script",
    "roblox projectile script",
    "roblox explosion script",
    "roblox damage script",
    "roblox heal script",
    "roblox buff script",
    "roblox debuff script",
    "roblox enemy script",
    "roblox boss script",
    "roblox wave system",
    "roblox tower defense script",
    "roblox simulator script",
    "roblox clicker script",
    "roblox idle script",
    "roblox incremental script",


    "roblox replicatedstorage",
    "roblox serverstorage",
    "roblox startergui",
    "roblox workspace",
    "roblox players service",
    "roblox runservice",
    "roblox userinputservice",
    "roblox contextactionservice",
    "roblox httpservice",
    "roblox marketplaceservice",
    "roblox badgeservice",
    "roblox datastoreservice",
    "roblox teleportservice",
    "roblox teams service",
    "roblox groupservice",
    "roblox physicsservice",
    "roblox collectionservice",
    "roblox pathfindingservice",
    "roblox soundservice",
    "roblox lighting service",


    "chatgpt for roblox",
    "chatgpt roblox scripts",
    "chatgpt luau",
    "gpt4 roblox",
    "claude roblox",
    "gemini roblox",
    "copilot roblox",
    "roblox github copilot",
    "roblox copilot alternative",
    "roblox ai alternative to chatgpt",
    "better than chatgpt for roblox",
    "roblox specific ai",
    "roblox dedicated ai tool",
    "ai trained on roblox",
    "ai trained on luau",
    "roblox ai vs chatgpt",
    "roblox ai vs gemini",
    "roblox ai vs claude",
    "roblox ai vs copilot",
    "roblox ai vs grok",
    "roblox ai vs cursor",
    "roblox ai vs replit",
    "chatgpt bad at luau",
    "chatgpt wrong luau syntax",
    "ai that knows luau",
    "ai that actually knows roblox",
    "roblox aware ai",
    "luau aware ai",


    "how to script roblox",
    "roblox script tutorial",
    "roblox scripting for beginners",
    "best roblox scripting tool",
    "roblox script maker",
    "generate roblox script",
    "write roblox script ai",
    "roblox script writer",
    "roblox code generator free",
    "roblox ai code",
    "ai for roblox developers",
    "how do i script in roblox",
    "how to make a roblox game with ai",
    "roblox scripting made easy",
    "easiest way to script roblox",
    "roblox no code tool",
    "roblox low code ai",
    "roblox beginner scripting tool",
    "roblox scripting for non coders",
    "roblox script help ai",
    "roblox script fixer ai",
    "fix my roblox script ai",
    "debug roblox script ai",
    "roblox error fixer",
    "roblox bug fixer ai",
    "explain roblox script ai",
    "roblox script explainer",
    "learn roblox scripting with ai",
    "roblox scripting faster",
    "speed up roblox development",
    "roblox productivity tool",
    "how to make a datastore in roblox",
    "how to make a shop in roblox",
    "how to make a combat system in roblox",
    "how to make an npc in roblox",
    "how to make a gui in roblox",
    "how to make a leaderboard in roblox",
    "how to make a tycoon in roblox",
    "how to make a pet system in roblox",
    "how to make a trading system roblox",
    "how to add anticheat to roblox game",
    "how to save player data roblox",
    "generate full roblox game system",
    "generate roblox module script",
    "generate roblox gui script",
    "generate roblox datastore script",
    "instant roblox scripts",
    "one prompt roblox scripts",
    "prompt to roblox script",
    "natural language roblox script",
    "describe and generate roblox script",
    "plain english roblox script",
    "no coding roblox script",
    "roblox script in seconds",
    "fastest roblox script generator",
    "production ready roblox scripts",
    "clean roblox scripts",
    "optimized roblox scripts",
    "typed roblox scripts",
    "working roblox scripts",


    "ai tool",
    "ai tools",
    "ai assistant",
    "ai helper",
    "ai writer",
    "ai coder",
    "ai generator",
    "ai bot",
    "free ai tool",
    "free ai tools",
    "free ai assistant",
    "free ai helper",
    "code generator",
    "script generator",
    "code writer",
    "script writer",
    "code helper",
    "script helper",
    "code assistant",
    "script assistant",
    "game ai",
    "game tool",
    "game helper",
    "game assistant",
    "game generator",
    "game coder",
    "game scripter",
    "game developer ai",
    "indie dev ai",
    "solo dev ai",
    "solo developer ai",
    "game jam ai tool",
    "roblox hackathon",


    "roblox ai discord",
    "roblox developer discord",
    "roblox scripting discord",
    "luau discord",
    "wisp discord",
    "roblox ai community",
    "roblox developer community",
    "roblox scripting community",
    "roblox script help discord",


    "roblox ai tiktok",
    "roblox ai youtube",
    "roblox ai review youtube",
    "roblox ai tutorial youtube",
    "roblox ai twitter",
    "roblox ai reddit",
    "roblox ai devforum",
    "new roblox ai tool",
    "new roblox tool 2025",
    "best new roblox tool",
    "roblox ai just dropped",
    "roblox ai just released",






    "wisp ai 2025",
    "wisp ai 2026",
    "wisp beta access",
    "wisp early access",
    "wisp script tool",
    "wisp roblox plugin",
    "wisp studio plugin",
    "wisp free plan",
    "wisp pro plan",
    "wisp pricing",
    "wisp how to use",
    "wisp getting started",
    "wisp signup",
    "wisp login",
    "wisp dashboard",
    "wisp projects",
    "wisp chat",
    "wisp generate",
    "wisp roblox ai platform",
    "wisp luau generator",
    "wisp code writer",
    "wisp script writer",
    "wisp roblox scripts",
    "wisp best roblox ai",
    "wisp ai tool review",
    "wisp vs chatgpt roblox",
    "wisp vs gpt4 roblox",
    "wisp vs gemini roblox",
    "wisp vs claude roblox",
    "wisp vs cursor roblox",
    "wisp vs replit roblox",
    "wisp vs copilot roblox",
    "wisp vs grok roblox",
    "wisp alternative",
    "wisp competitor",
    "wisp is the best",
    "is wisp free",
    "wisp free tier",
    "wisp trial",
    "wisp ai no signup",
    "wisp ai no account needed",
    "wisp ai for kids",
    "wisp ai for teens",
    "wisp ai for young devs",
    "wisp works with roblox studio",
    "wisp plugin roblox studio",
    "wisp api",
    "wisp webhook",
    "wisp token",
    "wisp session",
    "wisp datamodel",
    "wisp scan game",
    "wisp read game",
    "wisp context aware",
    "wisp knows your game",
    "wisp reads your workspace",
    "wisp game aware ai",


    "roblox ai ate",
    "roblox ai ate and left no crumbs",
    "roblox ai understood the assignment",
    "roblox ai went crazy",
    "roblox ai went off",
    "roblox ai is goated fr",
    "roblox ai periodt",
    "roblox ai slay",
    "roblox ai devs stay winning",
    "roblox ai core",
    "roblox ai on god",
    "roblox ai god tier",
    "roblox ai s tier",
    "roblox ai a tier",
    "roblox ai tier list",
    "roblox ai best tier",
    "roblox ai glow up",
    "roblox ai meta",
    "roblox ai current meta",
    "roblox ai meta 2025",
    "roblox scripting meta 2025",
    "roblox dev meta changed",
    "roblox dev meta ai",
    "roblox ai just different",
    "roblox ai not the same anymore",
    "roblox ai broke the game",
    "roblox scripting unlocked",
    "roblox ai unhinged in a good way",
    "roblox ai cooked",
    "roblox ai cooked fr",
    "roblox ai this is the way",
    "ai for roblox devs is here",
    "roblox ai literally built for this",
    "roblox ai tool built different",
    "roblox ai just built",
    "roblox devs eating good",
    "roblox dev W 2025",
    "roblox dev life changed",
    "roblox ai changed everything",


    "gpt 4o roblox scripts 2025",
    "gpt 4o mini roblox",
    "gpt 5 roblox scripts",
    "o3 roblox scripting",
    "o1 preview roblox",
    "o4 mini roblox",
    "claude 4 opus roblox",
    "claude haiku roblox",
    "claude haiku luau",
    "claude opus 4 luau",
    "claude sonnet 4 luau",
    "gemini 2.5 pro roblox",
    "gemini 2.5 flash roblox",
    "gemini ultra roblox",
    "gemini 1.5 roblox",
    "grok 2 roblox",
    "grok 3 luau",
    "grok free luau",
    "grok api roblox",
    "deepseek v3 roblox",
    "deepseek coder roblox",
    "deepseek v2 roblox",
    "deepseek luau",
    "llama 3 roblox",
    "llama 3.1 roblox",
    "llama 4 roblox",
    "llama luau scripts",
    "mistral large roblox",
    "mistral codestral roblox",
    "codestral luau",
    "qwen 2.5 roblox",
    "qwen coder roblox",
    "phi 4 roblox",
    "phi roblox scripts",
    "codellama roblox",
    "starcoder roblox",
    "codegemma roblox",
    "cohere roblox",
    "perplexity roblox ai",
    "you.com roblox",
    "poe ai roblox",
    "character ai roblox",
    "ai21 roblox",
    "together ai roblox scripts",
    "groq ai roblox",
    "groq fast luau",
    "fireworks ai roblox",
    "anyscale roblox",
    "modal roblox scripts",
    "replicate roblox",
    "openrouter roblox",
    "openrouter luau ai",


    "completely free roblox ai",
    "roblox ai free forever",
    "roblox ai free no limits",
    "roblox ai unlimited free",
    "roblox ai free tier unlimited",
    "roblox ai no rate limit",
    "roblox ai free daily limit",
    "roblox ai free tokens",
    "roblox ai pay nothing",
    "roblox ai zero cost",
    "roblox ai no wallet needed",
    "roblox ai no stripe",
    "free roblox ai for students",
    "free roblox ai for kids",
    "free roblox ai for teens",
    "roblox ai accessible",
    "roblox ai for everyone",
    "roblox ai democratized",
    "roblox scripting for everyone",
    "roblox ai open access",
    "roblox ai gratis",
    "roblox ai kostenlos",
    "roblox ai gratuit",
    "roblox ai gratis tool",
    "roblox gratis ai",
    "free roblox ai tool no login required",
    "roblox ai tool 2025 free no sign up",
    "roblox ai absolutely free",
    "roblox ai genuinely free",
    "roblox ai actually free",


    "luau signal pattern",
    "luau reactive programming",
    "luau observer pattern",
    "luau singleton pattern",
    "luau factory pattern",
    "luau proxy pattern",
    "luau decorator pattern",
    "luau state machine luau",
    "luau finite state machine",
    "luau behavior tree",
    "luau event driven",
    "luau promise library",
    "luau promise roblox",
    "roblox promise luau",
    "roblox async await luau",
    "luau yield patterns",
    "luau spawn task",
    "luau task.spawn",
    "luau task.delay",
    "luau task.wait",
    "luau task.defer",
    "luau parallel luau",
    "roblox parallel luau scripts",
    "luau actors roblox",
    "roblox actor model",
    "luau environment",
    "luau sandboxing",
    "luau closures",
    "luau upvalues",
    "luau varargs",
    "luau tuple",
    "luau multiple returns",
    "luau recursion",
    "luau memoize",
    "luau lazy evaluation",
    "luau functional programming",
    "luau immutable data",
    "luau deepcopy",
    "luau table clone",
    "luau table freeze",
    "luau setmetatable",
    "luau getmetatable",
    "luau __index",
    "luau __newindex",
    "luau __call",
    "luau __tostring",
    "luau __add",
    "luau __sub",
    "luau __mul",
    "luau __div",
    "luau __len",
    "luau __concat",
    "luau __eq",
    "luau __lt",
    "luau __le",
    "luau operator overloading",
    "luau typeof",
    "luau type assertion",
    "luau type narrowing",
    "luau union types",
    "luau intersection types",
    "luau optional types",
    "luau nil safety",
    "luau maybe type",
    "luau enum roblox",
    "luau enum pattern",
    "roblox enum luau",
    "luau benchmark",
    "luau performance",
    "luau optimization",
    "luau profiling",
    "luau memory",
    "luau gc",
    "roblox script performance",
    "roblox luau optimization tips",
    "roblox fast scripts",
    "roblox optimized code ai",
    "luau linting",
    "luau selene",
    "luau stylua",
    "luau lsp",
    "luau language server",
    "rojo roblox",
    "rojo workflow ai",
    "roblox git workflow",
    "roblox version control",
    "roblox ci cd",
    "roblox testing luau",
    "luau testez",
    "luau jest",
    "luau unit testing",
    "roblox tdd ai",


    "roblox rpg scripts",
    "roblox rpg system ai",
    "roblox open world scripts",
    "roblox survival game scripts",
    "roblox horror game scripts",
    "roblox escape room scripts",
    "roblox murder mystery scripts",
    "roblox battle royale scripts",
    "roblox zombie game scripts",
    "roblox military game scripts",
    "roblox ninja game scripts",
    "roblox anime game scripts",
    "roblox jojo roblox scripts",
    "roblox naruto game scripts",
    "roblox one piece roblox scripts",
    "roblox dragon ball roblox scripts",
    "roblox demon slayer scripts",
    "roblox blue lock roblox",
    "roblox racing game scripts",
    "roblox driving game scripts",
    "roblox drift script roblox",
    "roblox nascar roblox scripts",
    "roblox parkour game scripts",
    "roblox skateboard script",
    "roblox space game scripts",
    "roblox underwater game",
    "roblox fighting game scripts",
    "roblox pvp scripts",
    "roblox 1v1 scripts",
    "roblox arena scripts",
    "roblox mmo scripts",
    "roblox mmorpg system",
    "roblox dungeon scripts",
    "roblox quest system",
    "roblox dialogue system",
    "roblox npc dialogue",
    "roblox story game",
    "roblox visual novel",
    "roblox dating sim roblox",
    "roblox life game scripts",
    "roblox roleplay scripts",
    "roblox rp scripts",
    "roblox town game scripts",
    "roblox city game scripts",
    "roblox jail game scripts",
    "roblox prison scripts",
    "roblox police scripts",
    "roblox military roleplay",
    "roblox hospital scripts",
    "roblox school scripts",
    "roblox restaurant scripts",
    "roblox cooking game",
    "roblox kitchen script",
    "roblox retail scripts",
    "roblox store scripts",
    "roblox zombie survival ai",
    "roblox tower game scripts",
    "roblox minigame scripts",
    "roblox lobby system",
    "roblox game lobby ai",
    "roblox waiting room",
    "roblox intermission script",
    "roblox game voting",
    "roblox map picker",
    "roblox random map script",
    "roblox map rotation",
    "roblox event system",
    "roblox special event script",
    "roblox seasonal event",
    "roblox holiday event",
    "roblox halloween event",
    "roblox christmas event",
    "roblox new year event",
    "roblox limited time event",
    "roblox double xp event",


    "roblox friend system",
    "roblox follow system",
    "roblox party system",
    "roblox group system",
    "roblox clan system",
    "roblox guild system",
    "roblox alliance system",
    "roblox faction system",
    "roblox territory system",
    "roblox war system",
    "roblox diplomacy system",
    "roblox economy system",
    "roblox market system",
    "roblox stock market roblox",
    "roblox bank system",
    "roblox loan system",
    "roblox job system",
    "roblox work system",
    "roblox salary script",
    "roblox paycheck script",
    "roblox tax system",
    "roblox crime system",
    "roblox heist script",
    "roblox rob system",
    "roblox drug script",
    "roblox farming sim script",
    "roblox crop script",
    "roblox harvest script",
    "roblox animal script",
    "roblox breed script",
    "roblox egg script",
    "roblox hatch script",
    "roblox lucky script",
    "roblox chance system",
    "roblox gacha system",
    "roblox loot box script",
    "roblox drop system",
    "roblox drop rate",
    "roblox rarity system",
    "roblox common rare epic legendary",
    "roblox item rarity",
    "roblox item system",
    "roblox item database",
    "roblox item data script",
    "roblox weapon system",
    "roblox armor system",
    "roblox equipment system",
    "roblox gear system",
    "roblox loadout system",
    "roblox class system",
    "roblox role selection",
    "roblox hero selection",
    "roblox character selection",
    "roblox skin system",
    "roblox cosmetics system",
    "roblox hat system",
    "roblox accessory system",
    "roblox avatar editor",
    "roblox character customization",
    "roblox color customization",
    "roblox body type script",
    "roblox height script",
    "roblox scale script",
    "roblox humanoid script",
    "roblox r15 script",
    "roblox r6 script",
    "roblox r15 r6 converter",
    "roblox rig script",
    "roblox rig type ai",
    "roblox animation script",
    "roblox custom animation",
    "roblox animator ai",
    "roblox walk anim",
    "roblox run anim",
    "roblox idle anim",
    "roblox jump anim",
    "roblox swim anim",
    "roblox climb anim",
    "roblox emote script",
    "roblox emote system",
    "roblox dance script",
    "roblox taunt script",
    "roblox carry script",
    "roblox piggyback script",


    "roblox ui framework",
    "roblox ui library",
    "roblox topbar script",
    "roblox navbar script",
    "roblox sidebar script",
    "roblox menu script",
    "roblox pause menu",
    "roblox settings menu",
    "roblox options menu",
    "roblox hud script",
    "roblox hud system",
    "roblox minimap script",
    "roblox compass script",
    "roblox waypoint script",
    "roblox marker script",
    "roblox ui tween",
    "roblox ui animation",
    "roblox ui transition",
    "roblox open close gui",
    "roblox slide gui",
    "roblox fade gui",
    "roblox blur gui",
    "roblox popup script",
    "roblox notification script",
    "roblox toast notification",
    "roblox alert script",
    "roblox message script",
    "roblox hint script",
    "roblox tutorial script",
    "roblox onboarding script",
    "roblox tooltip script",
    "roblox context menu",
    "roblox right click menu",
    "roblox dropdown gui",
    "roblox checkbox script",
    "roblox toggle script",
    "roblox slider gui",
    "roblox progress bar script",
    "roblox loading bar script",
    "roblox health bar script",
    "roblox stamina bar",
    "roblox mana bar script",
    "roblox exp bar script",
    "roblox xp bar script",
    "roblox skill bar",
    "roblox hotbar script",
    "roblox action bar",
    "roblox ability bar",
    "roblox vote gui",
    "roblox vote script",
    "roblox poll script",
    "roblox store gui",
    "roblox shop gui",
    "roblox inventory gui",
    "roblox backpack gui",
    "roblox equipment gui",
    "roblox stats gui",
    "roblox profile gui",
    "roblox leaderboard gui",
    "roblox scoreboard gui",
    "roblox team gui",
    "roblox map gui",
    "roblox loading screen gui",
    "roblox custom loading screen",
    "roblox loading screen ai",
    "roblox cutscene gui",
    "roblox cinematic gui",
    "roblox credits gui",
    "roblox end screen",
    "roblox victory screen",
    "roblox defeat screen",
    "roblox game over screen",
    "roblox respawn screen",
    "roblox dead screen",
    "roblox spectate gui",
    "roblox waiting gui",
    "roblox countdown gui",
    "roblox timer gui",
    "roblox timer script",
    "roblox countdown script",
    "roblox clock script",
    "roblox date script roblox",


    "roblox robux script",
    "roblox robux prompt",
    "roblox premium check",
    "roblox premium reward",
    "roblox premium perks",
    "roblox gamepass check",
    "roblox gamepass reward",
    "roblox gamepass benefits",
    "roblox vip gamepass",
    "roblox double gamepass",
    "roblox speed gamepass",
    "roblox strength gamepass",
    "roblox donation script",
    "roblox tip script",
    "roblox support creator",
    "roblox developer product",
    "roblox limited item",
    "roblox sale event script",
    "roblox discount script",
    "roblox coupon script",
    "roblox promo code",
    "roblox code redemption",
    "roblox referral system",
    "roblox reward system",
    "roblox daily reward",
    "roblox login reward",
    "roblox streak reward",
    "roblox spin wheel script",
    "roblox lucky spin",
    "roblox daily spin",
    "roblox free reward script",
    "roblox event reward",
    "roblox seasonal reward",
    "roblox holiday reward",


    "roblox gravity script",
    "roblox custom gravity",
    "roblox low gravity script",
    "roblox zero gravity roblox",
    "roblox moon physics",
    "roblox space physics",
    "roblox water physics",
    "roblox buoyancy script",
    "roblox swim script",
    "roblox underwater script",
    "roblox flood script",
    "roblox lava script",
    "roblox ice script",
    "roblox sand script",
    "roblox mud script",
    "roblox quicksand script",
    "roblox bounce script",
    "roblox trampoline script",
    "roblox jump pad script",
    "roblox launch pad script",
    "roblox speed pad script",
    "roblox slow script",
    "roblox speed script",
    "roblox boost script",
    "roblox wind script",
    "roblox tornado script",
    "roblox wave script",
    "roblox tidal wave",
    "roblox earthquake script",
    "roblox volcano script",
    "roblox terrain script",
    "roblox terrain generation",
    "roblox procedural generation",
    "roblox noise terrain",
    "roblox perlin noise roblox",
    "roblox world generation ai",
    "roblox world builder ai",
    "roblox map generator",
    "roblox dungeon generator",
    "roblox maze generator",
    "roblox cave generator",
    "roblox city generator",
    "roblox building generator",
    "roblox room generator",
    "roblox tile map",
    "roblox grid system",
    "roblox chunk system",


    "roblox npc movement",
    "roblox npc follow",
    "roblox npc patrol",
    "roblox npc wander",
    "roblox npc attack",
    "roblox npc flee",
    "roblox npc idle",
    "roblox npc chase",
    "roblox npc dodge",
    "roblox npc heal",
    "roblox npc respawn",
    "roblox npc damage",
    "roblox npc kill",
    "roblox npc loot drop",
    "roblox npc health bar",
    "roblox npc name tag",
    "roblox npc overhead gui",
    "roblox npc hitbox",
    "roblox npc ragdoll",
    "roblox npc animation",
    "roblox npc sound",
    "roblox npc voice",
    "roblox npc speak",
    "roblox npc talk",
    "roblox npc interact",
    "roblox npc shop",
    "roblox vendor npc",
    "roblox quest giver npc",
    "roblox companion npc",
    "roblox guard npc",
    "roblox enemy npc",
    "roblox boss npc",
    "roblox miniboss",
    "roblox elite enemy",
    "roblox mob script",
    "roblox mob system",
    "roblox mob spawner",
    "roblox spawner script",
    "roblox spawn script",
    "roblox respawn script",
    "roblox spawn location",
    "roblox spawn cooldown",
    "roblox spawn protection",
    "roblox invincibility frames",
    "roblox iframes script",
    "roblox spawn animation",
    "roblox despawn script",
    "roblox destroy script",
    "roblox cleanup script",
    "roblox debris service",


    "roblox camera shake script",
    "roblox camera bob script",
    "roblox camera sway",
    "roblox camera tilt",
    "roblox camera zoom script",
    "roblox camera lock script",
    "roblox camera follow",
    "roblox camera orbit",
    "roblox camera cinematic",
    "roblox camera cutscene",
    "roblox spectate camera",
    "roblox free cam script",
    "roblox admin cam",
    "roblox god view script",
    "roblox overhead camera",
    "roblox top down camera",
    "roblox isometric camera",
    "roblox side scroller camera",
    "roblox 2.5d camera",
    "roblox fixed camera",
    "roblox security camera",
    "roblox cctv script",


    "roblox remote function",
    "roblox remote event script",
    "roblox server client communication",
    "roblox network ownership",
    "roblox replication script",
    "roblox server side validation",
    "roblox client prediction",
    "roblox lag compensation",
    "roblox network latency",
    "roblox ping script",
    "roblox tick rate",
    "roblox heartbeat script",
    "roblox throttle script",
    "roblox rate limit script",
    "roblox debounce script",
    "roblox cooldown script",
    "roblox event cooldown",
    "roblox action cooldown",
    "roblox attack cooldown",
    "roblox ability cooldown",
    "roblox fire rate script",
    "roblox reload script",
    "roblox ammo script",
    "roblox clip script",
    "roblox magazine script",
    "roblox gun reload script",


    "roblox keyboard input script",
    "roblox mouse script",
    "roblox mouse click script",
    "roblox mouse hover script",
    "roblox gamepad script",
    "roblox controller script",
    "roblox mobile input script",
    "roblox touch input script",
    "roblox swipe script",
    "roblox tap script",
    "roblox drag script",
    "roblox pinch zoom",
    "roblox joystick script",
    "roblox button script",
    "roblox keybind script",
    "roblox hotkey script",
    "roblox shortcut script",
    "roblox input map",
    "roblox action binding",
    "roblox multi key script",
    "roblox combo input",
    "roblox input buffer",
    "roblox input queue",
    "roblox input handler",
    "roblox input manager",


    "roblox sound manager",
    "roblox audio manager",
    "roblox music manager",
    "roblox sfx script",
    "roblox sound effect script",
    "roblox ambient sound",
    "roblox footstep sound",
    "roblox hit sound",
    "roblox death sound",
    "roblox respawn sound",
    "roblox jump sound",
    "roblox land sound",
    "roblox swim sound",
    "roblox explosion sound",
    "roblox gun sound",
    "roblox reload sound",
    "roblox level up sound",
    "roblox coin sound",
    "roblox purchase sound",
    "roblox notification sound",
    "roblox ui sound",
    "roblox button click sound",
    "roblox volume script",
    "roblox mute script",
    "roblox audio settings",
    "roblox 3d sound script",
    "roblox spatial audio",
    "roblox doppler sound",
    "roblox reverb script",
    "roblox echo script",
    "roblox equalizer script",


    "roblox vfx script",
    "roblox visual effects",
    "roblox particle effects",
    "roblox beam script",
    "roblox trail script",
    "roblox emission script",
    "roblox glow script",
    "roblox bloom script",
    "roblox blur script",
    "roblox fog script",
    "roblox shadow script",
    "roblox reflection script",
    "roblox neon script",
    "roblox fire script roblox",
    "roblox smoke script",
    "roblox water script",
    "roblox rain script",
    "roblox snow script",
    "roblox confetti script",
    "roblox firework script",
    "roblox lightning script",
    "roblox electric script",
    "roblox laser script",
    "roblox portal script",
    "roblox warp script",
    "roblox teleport effect",
    "roblox spawn effect",
    "roblox hit effect",
    "roblox blood script",
    "roblox wound script",
    "roblox shield effect",
    "roblox freeze effect",
    "roblox burn effect",
    "roblox poison effect",
    "roblox heal effect",
    "roblox buff effect",
    "roblox aura script",
    "roblox outline script",
    "roblox highlight script",
    "roblox tag script",
    "roblox indicator script",
    "roblox arrow script",
    "roblox ping indicator",


    "roblox lighting script roblox",
    "roblox time script",
    "roblox day cycle script",
    "roblox night cycle script",
    "roblox sun script",
    "roblox moon script",
    "roblox stars script",
    "roblox sky script",
    "roblox skybox script",
    "roblox atmosphere script",
    "roblox cloud script",
    "roblox weather system",
    "roblox storm script",
    "roblox thunder script",
    "roblox sunset script",
    "roblox sunrise script",
    "roblox ambient light",
    "roblox point light",
    "roblox surface light",
    "roblox spotlight script",
    "roblox flashlight script",
    "roblox dynamic lighting",
    "roblox colorgrading script",
    "roblox depth of field",
    "roblox motion blur",
    "roblox sun rays",
    "roblox lens flare",
    "roblox vignette script",


    "roblox save script",
    "roblox load script",
    "roblox autosave script",
    "roblox player data save",
    "roblox data migration",
    "roblox data backup",
    "roblox data wipe",
    "roblox data reset",
    "roblox cloud save",
    "roblox ordered datastore",
    "roblox sorted datastore",
    "roblox datastore leaderboard",
    "roblox global leaderboard",
    "roblox global ranking",
    "roblox top players",
    "roblox most wins",
    "roblox most kills",
    "roblox most coins",
    "roblox most xp",
    "roblox richest players",
    "roblox hall of fame",
    "roblox session script",
    "roblox session data",
    "roblox session lock",
    "roblox profile lock",
    "roblox data queue",
    "roblox retry logic",
    "roblox pcall datastore",
    "roblox error handling",
    "roblox data validation",
    "roblox schema validation",
    "roblox data structure",
    "roblox data normalization",
    "roblox data compression",
    "roblox serialize deserialize",
    "roblox json encode decode",
    "roblox httpservice json",
    "roblox external api",
    "roblox webhook script",
    "roblox discord webhook",
    "roblox slack webhook",
    "roblox analytics script",
    "roblox telemetry script",
    "roblox logging script",
    "roblox debug script",


    "roblox admin commands",
    "roblox admin system",
    "roblox admin panel",
    "roblox admin gui",
    "roblox mod commands",
    "roblox moderator script",
    "roblox rank check",
    "roblox permission system",
    "roblox whitelist script",
    "roblox blacklist script",
    "roblox ban system",
    "roblox tempban script",
    "roblox permaban script",
    "roblox kick reason script",
    "roblox warn script",
    "roblox warning system",
    "roblox mute script roblox",
    "roblox mute system",
    "roblox chat mute",
    "roblox chat ban",
    "roblox chat log",
    "roblox chat history",
    "roblox anti exploit",
    "roblox exploit detection",
    "roblox speed check",
    "roblox fly check",
    "roblox noclip check",
    "roblox teleport check",
    "roblox damage check",
    "roblox sanity check",
    "roblox server sided anticheat",
    "roblox server side check",
    "roblox server validation",
    "roblox secure coding roblox",
    "roblox remote event security",
    "roblox fireserver security",
    "roblox invokeclient security",
    "roblox ddos protection",
    "roblox spam protection",


    "roblox debug gui",
    "roblox fps counter",
    "roblox ping display",
    "roblox memory display",
    "roblox performance monitor",
    "roblox frame time",
    "roblox server stats",
    "roblox player count display",
    "roblox log script",
    "roblox print all players",
    "roblox dev console",
    "roblox testing script",
    "roblox studio playtest",
    "roblox simulate script",
    "roblox mock script",
    "roblox unit test luau",
    "roblox integration test",
    "roblox test runner",
    "roblox test suite",
    "roblox coverage luau",
    "roblox ci pipeline roblox",
    "roblox build script",
    "roblox deploy script",
    "roblox publish script",
    "roblox live update",
    "roblox hot reload",
    "roblox script reload",


    "roblox chat system custom",
    "roblox custom chat script",
    "roblox chat bubble script",
    "roblox proximity chat",
    "roblox voicechat script",
    "roblox team chat script",
    "roblox global chat",
    "roblox whisper script",
    "roblox dm script",
    "roblox private message",
    "roblox channel chat",
    "roblox trade chat",
    "roblox trade request",
    "roblox friend request",
    "roblox party request",
    "roblox invite system",
    "roblox invite link",
    "roblox referral code",
    "roblox clan invite",
    "roblox group invite",
    "roblox notification system",
    "roblox push notification",
    "roblox alert system",
    "roblox message system",
    "roblox inbox script",
    "roblox mail system",


    "roblox experience guidelines",
    "roblox terms of service compliant scripts",
    "roblox tos safe scripts",
    "roblox safe scripts",
    "roblox family friendly scripts",
    "roblox age rating",
    "roblox content maturity",
    "roblox age check script",
    "roblox place restrictions",
    "roblox private server script",
    "roblox vip server",
    "roblox reserved server",
    "roblox matchmaking script",
    "roblox auto matchmaking",
    "roblox team balancing",
    "roblox fill server",
    "roblox server list",
    "roblox server browser",
    "roblox region select",
    "roblox locale script",
    "roblox language script",
    "roblox translation script",
    "roblox localization",
    "roblox multi language",
    "roblox accessibility script",
    "roblox colorblind mode",
    "roblox font size script",
    "roblox ui scale",


    "how to make roblox game ai",
    "how to make roblox scripts with ai",
    "how to use ai for roblox",
    "how to generate roblox scripts",
    "how to get free roblox scripts",
    "how to write luau with ai",
    "how to code roblox game fast",
    "how to learn roblox scripting fast",
    "how to make roblox game faster",
    "how to automate roblox scripting",
    "how to use chatgpt for roblox",
    "how to use claude for roblox",
    "how to use gemini for roblox",
    "how to use grok for roblox",
    "is there an ai for roblox scripting",
    "can ai write roblox scripts",
    "can ai make roblox games",
    "can chatgpt write luau",
    "does ai know luau",
    "best ai for luau scripting",
    "best ai for roblox studio",
    "best tool for roblox scripts",
    "best way to write roblox scripts",
    "best roblox script tool 2025",
    "best free roblox coding tool",
    "best free roblox dev tool 2025",
    "what is the best roblox ai",
    "what ai should i use for roblox",
    "should i use chatgpt or wisp for roblox",
    "roblox ai recommendation",
    "top roblox ai tools",
    "top 5 roblox ai tools",
    "top 10 roblox ai tools",
    "roblox ai ranking",
    "roblox ai comparison",
    "roblox ai review 2025",
    "wisp vs competitors",


    "roblox developer quality of life",
    "roblox dev tools 2025",
    "roblox studio productivity",
    "roblox boilerplate code",
    "roblox starter code",
    "roblox template scripts",
    "roblox code templates",
    "roblox starter pack scripts",
    "roblox scaffold script",
    "roblox starter project",
    "roblox game kit",
    "roblox game framework",
    "roblox game engine tools",
    "roblox rapid prototyping",
    "roblox prototype fast",
    "roblox mvp fast",
    "roblox minimum viable game",
    "roblox game jam tools",
    "roblox 24 hour game",
    "roblox fast game dev",
    "roblox speedrun dev",
    "roblox dev sprint",
    "roblox hackathon tools",
    "roblox code review ai",
    "roblox code audit",
    "roblox code quality",
    "roblox clean code",
    "roblox best practices",
    "roblox style guide ai",
    "roblox code standards",
    "roblox readable code",
    "roblox maintainable code",
    "roblox scalable code",
    "roblox reusable code",
    "roblox modular code",
    "roblox decoupled code",
    "roblox solid principles roblox",
    "roblox dry code",
    "roblox refactor script",
    "roblox refactor ai",
    "roblox technical debt",
    "roblox legacy script fix",
    "roblox script conversion",
    "roblox convert old script",
    "roblox update script",
    "roblox script upgrade",
    "roblox old api migration",
    "roblox deprecated api fix",
    "roblox deprecated functions",


    "adopt me scripts",
    "bloxburg scripts",
    "brookhaven scripts",
    "royale high scripts",
    "arsenal scripts",
    "phantom forces scripts",
    "mm2 scripts",
    "murderer mystery scripts",
    "jailbreak scripts",
    "natural disaster survival",
    "tower of hell scripts",
    "piggy roblox scripts",
    "doors roblox scripts",
    "pet simulator scripts",
    "bee swarm simulator scripts",
    "loomian legacy scripts",
    "sols rng scripts",
    "blox fruits scripts",
    "shindo life scripts",
    "hero academia game roblox",
    "bad business scripts",
    "da hood scripts",
    "westbound scripts",
    "wild west roblox scripts",
    "age of empires roblox",
    "roblox bedwars scripts",
    "ro ghoul scripts",
    "dragon ball rage scripts",
    "project slayers scripts",
    "slayers unleashed scripts",
    "a bizarre day scripts",
    "yba scripts roblox",
    "stands awakening scripts",
    "grand piece online scripts",
    "all star tower defense",
    "tds scripts roblox",
    "rogue lineage scripts",
    "arcane odyssey scripts",
    "deepwoken scripts",
    "vesteria scripts",


    "roblox knockback formula",
    "roblox damage formula",
    "roblox dps script",
    "roblox crit script",
    "roblox critical hit",
    "roblox miss chance",
    "roblox dodge chance",
    "roblox block chance",
    "roblox armor penetration",
    "roblox damage reduction",
    "roblox elemental damage",
    "roblox weakness system",
    "roblox resistance system",
    "roblox immunity script",
    "roblox shield script",
    "roblox barrier script",
    "roblox absorb script",
    "roblox reflect script",
    "roblox thorns script",
    "roblox counter attack",
    "roblox riposte script",
    "roblox lifesteal script",
    "roblox health drain",
    "roblox energy drain",
    "roblox mana drain",
    "roblox stamina drain",
    "roblox aggro script",
    "roblox threat system",
    "roblox taunt script roblox",
    "roblox tank class script",
    "roblox healer class script",
    "roblox dps class script",
    "roblox support class script",
    "roblox range class script",
    "roblox melee class script",
    "roblox magic class script",
    "roblox assassin class script",
    "roblox stealth script",
    "roblox invisible script",
    "roblox sneak script",
    "roblox sight range script",
    "roblox line of sight",
    "roblox vision script",
    "roblox fog of war",
    "roblox minimap fog",


    "roblox generate game idea",
    "roblox game design ai",
    "roblox game concept ai",
    "roblox pitch ai",
    "roblox game document ai",
    "roblox gdd ai",
    "roblox game design document",
    "roblox game loop script",
    "roblox core loop",
    "roblox progression loop",
    "roblox retention mechanics",
    "roblox engagement script",
    "roblox session length",
    "roblox playtime tracker",
    "roblox first time user experience",
    "roblox ftue script",
    "roblox onboarding flow",
    "roblox new player experience",
    "roblox tutorial system",
    "roblox hint system",
    "roblox objective system",
    "roblox mission system",
    "roblox bounty system",
    "roblox side quest script",
    "roblox main quest script",
    "roblox story script",
    "roblox lore script",
    "roblox cutscene system",
    "roblox cinematic system",
    "roblox storyboard roblox",


    "roblox devforum 2025",
    "roblox devex 2025",
    "roblox creator hub",
    "roblox creator marketplace",
    "roblox creator store",
    "roblox toolbox ai",
    "roblox asset store ai",
    "roblox model store",
    "roblox plugin store",
    "roblox open source scripts",
    "roblox github scripts",
    "roblox free modules",
    "roblox open source modules",
    "roblox community scripts",
    "roblox script share",
    "roblox pastebin scripts",
    "roblox v3rmillion",
    "roblox script showcase",
    "roblox script release",
    "roblox creator program",
    "roblox developer event",
    "roblox rdc 2025",
    "roblox developers conference",
    "roblox creator challenge",
    "roblox game jam",
    "roblox accelerator",
    "roblox incubator",
    "roblox grant",
    "roblox funding",
    "roblox monetize game",
    "roblox earn robux",
    "roblox passive income",
    "roblox full time developer",
    "roblox professional developer",
    "roblox dev career",
    "roblox job",
    "roblox hire developer",
    "roblox freelance scripter",
    "roblox scripter for hire",
    "roblox commission scripter",
    "roblox dev portfolio",
    "roblox resume",
    "roblox interview prep",
    "roblox dev skills",
    "roblox dev learning",
    "roblox learn to code",
    "roblox coding course",
    "roblox scripting course",
    "roblox youtube tutorial",
    "roblox tiktok tutorial",
    "roblox shorts tutorial",
    "roblox scripting for kids course",
    "roblox coding for beginners youtube",
    "roblox youtube channel scripts",
    "roblox influencer dev",
  ],
  authors: [{ name: "Wisp Studios" }],
  icons: {
    icon: "/icons/favicon.ico",
    shortcut: "/icons/favicon.ico",
    apple: "/icons/apple-touch-icon.png",
  },
  openGraph: {
    title: "Wisp AI",
    description: "AI-powered Roblox script generation",
    type: "website",
    url: "https://wisp-pvv1.onrender.com",
    images: [
      {
        url: "/icons/CD1CB55E-5059-4BAA-B236-7C57F0A49F5B.png",
        width: 1200,
        height: 630,
        alt: "Wisp AI",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Wisp AI",
    description: "AI-powered Roblox script generation",
    images: ["/icons/CD1CB55E-5059-4BAA-B236-7C57F0A49F5B.png"],
  },
};

export const viewport: Viewport = {
  themeColor: "#060810",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <div className="app-content">{children}</div>
      </body>
    </html>
  );
}

//keywords generated with ai lol